[package]
name = "ternary-operator-macro"
version = "0.1.0"
edition = "2021"
description = "rust"
authors = ["zhubby yanvalue@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
